[theme]
base = "dark"
primaryColor = "#ff6b6b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "monospace"

[global]
# Wide mode by default
dataFrameSerialization = "arrow"

[server]
# Ensures proper serving
headless = true
enableCORS = false
enableXsrfProtection = false